package com.fauxx.sync.crypto

import com.goterl.lazysodium.interfaces.Box
import java.util.Base64

/**
 * This device's long-lived pairing identity: an X25519 keypair generated by libsodium's
 * `crypto_box_keypair`, byte-compatible with the desktop `dryoc` build.
 *
 * The public key is freely shareable (QR, mDNS TXT). The secret key is held privately here and
 * never exposed through any public API, [toString], or log. The secret never reaches SQLite
 * plaintext; persistence is the caller's job via [com.fauxx.sync.crypto.DeviceKeyStore], which
 * Tink-AEAD-wraps the `public || secret` blob.
 *
 * Note on zeroize-on-drop: the desktop wraps the secret in a type whose `Drop` zeroizes the bytes.
 * The JVM has no deterministic destructor and cannot reliably wipe a `ByteArray` via finalizers, and
 * this identity is a process-lifetime singleton (held by [com.fauxx.sync.SealedChannel]), so there is
 * no natural drop point. The transient persistence blobs ARE zeroed (see `DeviceKeyStore`); the live
 * in-identity copy intentionally is not. This divergence from the desktop's zeroize-on-drop is a
 * platform limitation, not an oversight.
 */
class DeviceIdentity private constructor(
    /** This device's X25519 public key (32 bytes), safe to share. */
    val publicKey: ByteArray,
    private val secretKey: ByteArray
) {

    /**
     * Seal [plaintext] for [recipientPublicKey], authenticated as coming from this device.
     * Draws a fresh 24-byte nonce from the OS CSPRNG (never reused) and returns a
     * self-describing [SealedEnvelope] carrying the nonce and the ciphertext+MAC.
     */
    fun seal(recipientPublicKey: ByteArray, plaintext: ByteArray): SealedEnvelope {
        require(recipientPublicKey.size == Box.PUBLICKEYBYTES) {
            "recipient public key is ${recipientPublicKey.size} bytes, expected ${Box.PUBLICKEYBYTES}"
        }
        val nonce = ByteArray(Box.NONCEBYTES)
        SodiumProvider.secureRandom.nextBytes(nonce)
        val ciphertext = ByteArray(plaintext.size + Box.MACBYTES)
        val ok = SodiumProvider.box.cryptoBoxEasy(
            ciphertext, plaintext, plaintext.size.toLong(), nonce, recipientPublicKey, secretKey
        )
        check(ok) { "crypto_box_easy seal failed" }
        return SealedEnvelope(nonce, ciphertext)
    }

    /**
     * Open a [SealedEnvelope] that [senderPublicKey] sealed for this device. Returns the
     * plaintext on success, or `null` on authentication failure (a forged, tampered, or
     * unpaired-sender frame) so callers fail closed without leaking which check failed.
     */
    fun open(senderPublicKey: ByteArray, envelope: SealedEnvelope): ByteArray? {
        if (senderPublicKey.size != Box.PUBLICKEYBYTES) return null
        if (envelope.nonce.size != Box.NONCEBYTES) return null
        if (envelope.ciphertext.size < Box.MACBYTES) return null
        val plaintext = ByteArray(envelope.ciphertext.size - Box.MACBYTES)
        val ok = SodiumProvider.box.cryptoBoxOpenEasy(
            plaintext, envelope.ciphertext, envelope.ciphertext.size.toLong(),
            envelope.nonce, senderPublicKey, secretKey
        )
        return if (ok) plaintext else null
    }

    /**
     * Borrow a COPY of the raw secret-key bytes for persistence into the Tink-wrapped keystore
     * only. Module-internal (the desktop analog is a crate-private accessor) so no public API,
     * [toString], or log can reach the secret. The caller MUST zero the returned buffer after use.
     */
    internal fun secretKeyCopyForKeystore(): ByteArray = secretKey.copyOf()

    /** Redacts the secret; only the (public, safe) base64url public key is rendered. */
    override fun toString(): String =
        "DeviceIdentity(publicKey=${Base64.getUrlEncoder().withoutPadding().encodeToString(publicKey)}, secretKey=<redacted>)"

    companion object {
        /** Generate a fresh device identity from the OS CSPRNG. */
        fun generate(): DeviceIdentity {
            val pk = ByteArray(Box.PUBLICKEYBYTES)
            val sk = ByteArray(Box.SECRETKEYBYTES)
            val ok = SodiumProvider.box.cryptoBoxKeypair(pk, sk)
            check(ok) { "crypto_box_keypair generation failed" }
            return DeviceIdentity(pk, sk)
        }

        /**
         * Reconstruct an identity from persisted key bytes. Rejects wrong-length input by failing
         * closed (mirrors the desktop `from_bytes`), never padding or truncating. Defensively
         * copies so the caller can zero its transient buffers.
         */
        fun fromBytes(publicKey: ByteArray, secretKey: ByteArray): DeviceIdentity {
            require(publicKey.size == Box.PUBLICKEYBYTES) {
                "device public key is ${publicKey.size} bytes, expected ${Box.PUBLICKEYBYTES}"
            }
            require(secretKey.size == Box.SECRETKEYBYTES) {
                "device secret key is ${secretKey.size} bytes, expected ${Box.SECRETKEYBYTES}"
            }
            return DeviceIdentity(publicKey.copyOf(), secretKey.copyOf())
        }
    }
}
