package com.fauxx.sync.data

import androidx.room.Dao
import androidx.room.Entity
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.PrimaryKey
import androidx.room.Query
import kotlinx.coroutines.flow.Flow

/**
 * An inbound, authenticated synced persona (E13 #178), keyed on the persona's own `id` so that
 * re-delivering the idempotent `PersonaUpsert` converges to the same row instead of piling up
 * duplicates (contract sections 5.3 / 7; AC-4).
 *
 * Design note: the existing `persona_history` table keys on an autogenerated `Long`, not the
 * persona `id`, so a naive insert there would append on every re-delivery. Per the E13 brief's
 * recommendation, synced personas land in this dedicated `id`-keyed table. Wiring a synced persona
 * into the active rotation (vs. mere receipt + transparency) is a documented follow-up.
 */
@Entity(tableName = "synced_personas")
data class SyncedPersonaEntity(
    @PrimaryKey val id: String,
    val personaJson: String,
    val receivedAt: Long
)

/** DAO for received synced personas. Idempotent upsert keyed on the persona `id`. */
@Dao
interface SyncedPersonaDao {

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsert(entry: SyncedPersonaEntity)

    @Query("SELECT * FROM synced_personas WHERE id = :id")
    suspend fun getById(id: String): SyncedPersonaEntity?

    @Query("SELECT * FROM synced_personas ORDER BY receivedAt DESC")
    suspend fun getAll(): List<SyncedPersonaEntity>

    @Query("SELECT * FROM synced_personas ORDER BY receivedAt DESC")
    fun observeAll(): Flow<List<SyncedPersonaEntity>>

    @Query("DELETE FROM synced_personas")
    suspend fun deleteAll()
}
